# Generated by Django 5.1.6 on 2025-03-25 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task_updated_at_alter_user_email_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
    ]
